// This file was generated by counterfeiter
package fakes

import (
	"os/exec"
	"sync"

	"github.com/julz/garden-runc"
)

type FakeContainerCmder struct {
	CmdStub        func(path string, args ...string) *exec.Cmd
	cmdMutex       sync.RWMutex
	cmdArgsForCall []struct {
		path string
		args []string
	}
	cmdReturns struct {
		result1 *exec.Cmd
	}
}

func (fake *FakeContainerCmder) Cmd(path string, args ...string) *exec.Cmd {
	fake.cmdMutex.Lock()
	fake.cmdArgsForCall = append(fake.cmdArgsForCall, struct {
		path string
		args []string
	}{path, args})
	fake.cmdMutex.Unlock()
	if fake.CmdStub != nil {
		return fake.CmdStub(path, args...)
	} else {
		return fake.cmdReturns.result1
	}
}

func (fake *FakeContainerCmder) CmdCallCount() int {
	fake.cmdMutex.RLock()
	defer fake.cmdMutex.RUnlock()
	return len(fake.cmdArgsForCall)
}

func (fake *FakeContainerCmder) CmdArgsForCall(i int) (string, []string) {
	fake.cmdMutex.RLock()
	defer fake.cmdMutex.RUnlock()
	return fake.cmdArgsForCall[i].path, fake.cmdArgsForCall[i].args
}

func (fake *FakeContainerCmder) CmdReturns(result1 *exec.Cmd) {
	fake.CmdStub = nil
	fake.cmdReturns = struct {
		result1 *exec.Cmd
	}{result1}
}

var _ gardenrunc.ContainerCmder = new(FakeContainerCmder)
