// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/julz/garden-runc"
)

type FakeDepot struct {
	CreateStub        func() (string, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct{}
	createReturns struct {
		result1 string
		result2 error
	}
}

func (fake *FakeDepot) Create() (string, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct{}{})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub()
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *FakeDepot) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeDepot) CreateReturns(result1 string, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

var _ gardenrunc.Depot = new(FakeDepot)
