#!/bin/sh

export GODEPS_WORKSPACE=$PWD/Godeps/_workspace
export GOPATH=$GODEPS_WORKSPACE:$GOPATH
export PATH=$GODEPS_WORKSPACE/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race -keepGoing -nodes=4 "$@"
